### ISSUE TITLE
System running too fast - getting serious GOT errors

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-core#109]
Can we move back to cloud at cost ASAP? Getting serious GOT errors.

When I open a question page I like to take the 52 minute page load time to watch an episode of game of thrones and eat some cookies - now I have to start voting immediately :-(

Either we move back to CAC's high powered network cobbled together out of old Argus electronic toasters and Currys €4 pen drives or we get Tyrion Lannister to moderate the questions and just overlook the inevitable barrage of eunuch and brothel jokes - explain to people it's a quirk of Python 2.7.9's JSON library.

Those who disagree can look forward to liaising with Ramsey Bolton and his woodwork tools later this week.

**Comment by pietrosperoni** [comment]
Unfortunately we can't go back.But help us to invite enough people, and the waiting time will start increasing again.
