### ISSUE TITLE
implement lost password api call

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#13]
implement functions and settings according to the rules below. UI delegated to vilfredo-client repo issue tracking.

![slide1](https://cloud.githubusercontent.com/assets/180794/4737950/39e62266-59f9-11e4-8691-ea8f2e31a79b.PNG)
![slide2](https://cloud.githubusercontent.com/assets/180794/4737947/39db481e-59f9-11e4-8559-6cbba784f9af.PNG)
![slide3](https://cloud.githubusercontent.com/assets/180794/4737948/39e392a8-59f9-11e4-8534-8b2296838e3b.PNG)
![slide4](https://cloud.githubusercontent.com/assets/180794/4737949/39e5500c-59f9-11e4-9d2a-b29212f26096.PNG)

**Comment by derekpa** [comment]
Documentation is updated
