### ISSUE TITLE
Write-up vilfredo specific github issues usage document

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-core#14]
It is really useful to have a document which covers what labels are used how and what the workflows are for new-features, what for bugs. It does not need to be longer then a page probably but I find it helps a lot to have something written up. (it is very hard to improve a process which is not written down).

Here is a sample one I did for another project.
https://docs.google.com/a/vorski.com/document/d/1XgKwm1I7EqgGvPwcMEJzL6CaFEwv_z2-AZWMFTTqrrg/edit

**Comment by giovanisp** [comment]
Hi @vvorski we are due to release by the end of this week. Do you think you can close this, or shall I move it to the next release ?  Thank you.

**Comment by vvorski** [comment]
Everything seems to be working well
