### ISSUE TITLE
add longer expire headers for static resources

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#19]
static resources (under /static) do not have far future expire headers for better cache. Need to add it to the web server conf.

**Comment by derekpa** [comment]
Well static.vilfredo.org still needs to be pointed to the static folder before we do this

**Comment by giovanisp** [comment]
@pietrosperoni, wasn't that already in place?

**Comment by derekpa** [comment]
What? the static subdomain doesn't point anywhere. @pietrosperoni has to set this.

**Comment by pietrosperoni** [comment]
In dreamhost you don't seem to be able to point a subdirectory into a folder. Just into another subdrectory.

![screen shot 2015-01-19 at 17 58 48](https://cloud.githubusercontent.com/assets/1333674/5804211/7d5f089a-a004-11e4-81ce-f761bead7572.png)

**Comment by giovanisp** [comment]
mod_pagespeed is enough for now.
