### ISSUE TITLE
The domination is not working!

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-core#34]
Right now we are using the domination and it should be the new domination. Where if someone declares he does not understand a proposal he is not considered in deciding who dominaes what for that proposal.

Now if we look at proposal 26 
![screen shot 2014-12-30 at 11 19 24](https://cloud.githubusercontent.com/assets/1333674/5577606/3877afec-9015-11e4-8d3e-9bee10a3f050.png)
It is only understood by user Pietro.

So all the others should not be considered in deciding who dominates what. Now in the pareto graph is appears that 26 is being strongly dominated by 7, and does not dominate anything.
![screen shot 2014-12-30 at 11 21 14](https://cloud.githubusercontent.com/assets/1333674/5577621/8b25899e-9015-11e4-902c-471f88ba2eeb.png)

 But actually it should be partially dominated by all proposals liked by Pietro, for example proposal 25.

But many many others too. In fact 14 proposals should partially dominate 26. See the third image:

![screen shot 2014-12-30 at 11 22 47](https://cloud.githubusercontent.com/assets/1333674/5577631/b90029be-9015-11e4-8c32-5e8e37d417af.png)

So we are definitely doing something wrong, or maybe just using the old dominance system. But even in that case there should be no one liking it (all the people who voted for 26 voted on the left side of the triangle, so they all are considered as voting against) so it should actually be dominated by a LOT of proposals. So even in that case there is obviously a bug.

So first question:
1) is this the new or the old domination system?
2) If it is the new domination system it has a bug
3) if it is the old domination system it has a bug AND we also need to move to the new domination system.

Cheers,
Pietro

**Comment by derekpa** [comment]
OK, I looked at the data and simply looking at that case of 26 (partially understood) with regards to the new algorithm, yes there are many partial dominations, but one partial domination from 7 converts using the theorem to a full domination. Therefore it gets added to the graph in step 5, ignoring the partials, hence it appears where it does, below (fully dominated by - via the theorem) proposal 7.

If this is wrong we need to look again at the algorithm or go over the mindmap.

**Comment by pietrosperoni** [comment]
Ah ha! This is great. So it looks like the result is good (me very happy), just it is not explained. Ok, in the next version we definitely need to have some text explaining for every dominance and partial dominance why is it so. I'll add it in the todo list for the next release. Thanks.

**Comment by derekpa** [comment]
Well I suppose if the mathematician doesn't understand it then the system probably does need a way of explaining the results :-)

**Comment by derekpa** [comment]
PS Me also very happy.

**Comment by derekpa** [comment]
Although I'm surprised the voting graph and results map above aren't abundantly self explanatory on their own. A quick glance should ell you all you need to know. :-P

**Comment by pietrosperoni** [comment]
Actually the idea to show the relation between two proposals on the triangle is going around my head from some time.
It should show only those 2 proposals, the center of the triangle, and how everybody voted.

Then using colors we might be able to give a sense of who is doing what. Like if a person did not understand one or both of the proposals his votes should be in Grey. If a person understands both his votes should be in green. If a person disagrees with both his votes should be in red. And if a person agrees with only 1 and not the other his votes should be Orange (agree with A but not with B) or Blue (agree with B but not with A).
In fact those last ones are the only interesting information. As long as there is something Orange and nothing Blue, then A dominates B.
Something Blue and nothing Orange and B dominates A.
Nothing Grey: Complete dominations.

And the theorem is a bit more complicated....

**Comment by giovanisp** [comment]
@pietrosperoni add this last comment as a new issue, pls.

**Comment by pietrosperoni** [comment]
ok

**Comment by pietrosperoni** [comment]
Added as https://github.com/fairdemocracy/vilfredo-client/issues/116
