### ISSUE TITLE
implement API for user photo upload and retrieval

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#35]
receive a user uploaded photo (max 5mb for instance), store the original file (named "SOME_SALTED_HASH".png), and store the cropped image (square) sent by the user (named "<SOME_SALTED_HASH-thumb.png").

send the user profile photos url whenever required (both files should be hosted under /static/usercontent/profiles/...)

**Comment by giovanisp** [comment]
We are not cropping and storing the thumbnail. 
It is a huge performance issue, since we load everytime the full image for each small thumbnail to show:

![image](https://cloud.githubusercontent.com/assets/180794/6370221/7ae46dba-bcee-11e4-8e84-2e24bfb8a5a6.png)

**Comment by derekpa** [comment]
Won't have time to do this before next release. Shall I just remove avatars from the client for now?

**Comment by giovanisp** [comment]
No. Keep them and let's move the thumbnail for 2.0 final.

**Comment by derekpa** [comment]
ok

**Comment by giovanisp** [comment]
thumbs back to 2.0 final.

**Comment by giovanisp** [comment]
Ok. Out of curiosity, why don't we add the "-thumb.png" suffix in the image thumbnail and keep both versions (full and thumb) ? Then when we remove we can remove HASH*.*  anyway.

**Comment by derekpa** [comment]
Why would we keep both versions?

never heard of adding thumbs suffix. What's the point?

**Comment by giovanisp** [comment]
> Why would we keep both versions?
> 
In the future we can improve the upload allowing cropping, resizing the original image. So we will already have it for past users.

> never heard of adding thumbs suffix. What's the point?
> 
Quite common. Good maintenance of files in filesystem, and ease of mgmt (just delete hash*) 
Wordpress keeps even more sizes for each image uploaded depending on the theme used.

**Comment by derekpa** [comment]
> Good maintenance of files in filesystem, and ease of mgmt (just delete hash*)
Well we have currently have that by keeping all our avatars in one place in the file system, and we're only storing thumbs.

 We can certainly keep the originals.

**Comment by giovanisp** [comment]
Ok, so when you keep the originals, the thumbs need a suffix to be easily identified :-)

**Comment by derekpa** [comment]
Yes, so -thumb gets added to the filename :-)
