### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-core#41]
I got an invite as follows:

   Hi!

   Pietro invites you to participate in the question "How should I plant the green roof in the house in Portugal?" on Vilfredo.

   If you wish to participate please click on the link below and follow the instructions.

   Click to participate: http://vilfredo.org/invitation?email=victor@vorski.com&eit=7e0c651502be4f55bc6293c915610f67

when I try to register I get a you must use cookies message and I can't register. I am on Chrome-latest

![screen shot 2015-02-06 at 11 15 30](https://cloud.githubusercontent.com/assets/1789426/6078528/999aa690-adf1-11e4-8bcd-a96c02fd439b.png)

**Comment by giovanisp** [comment]
Interesting. You do not see the bottom toolbar asking your consent to treat cookies (EU Cookie Law). Have you tried cleaning cache (if you used the old vilfredo) and accessing the URL again ?

**Comment by vvorski** [comment]
Yes, I tried another browser and it worked. thank you.

(not willing to dump cache on my primary browser! ;) )


Victor Vorski
victor@vorski.com　skype:vvorski

**Comment by giovanisp** [comment]
cheers!

**Comment by giovanisp** [comment]
@derekpa take a look anyway if the cookies are different for demo.vilfredo.org, nightly.vilfredo.org and www.vilfredo.org  .... the fact that he did not saw the toolbar but the system identified he could not login because the lack of cookie acceptance could be somehow related to it ?

**Comment by derekpa** [comment]
Could be a cache issue.

**Comment by pietrosperoni** [comment]
…everything is a cache issue…

**Comment by giovanisp** [comment]
@pietrosperoni cache issues are very common among early adopters of a fast changing environment. Chrome is known to cache more than it should to optimize performance, that's why it is advisable to navigate in "incognito" mode when testing, so you make sure the browser is not doing anything it shouldn't. 
anyway @derekpa, as much as you can, when deploying restart the webserver, it should clear objects in cache.
