### ISSUE TITLE
remove user email from invitation URL

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#42]
the hash code already identifies (hopefully) the user being invited and can get his email, so let's get rid of plain emails in the invitation url like:

Click to participate: http://vilfredo.org/invitation?email=name@example.com&eit=0e0c654353be4f55bc6293c915610f67

**Comment by giovanisp** [comment]
See also #43

**Comment by derekpa** [comment]
email is already removed.
