### ISSUE TITLE
I can see the text of question I do not participate

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#46]
I am not invited or a member of this question https://vilfredo.org/question/3  still I can read it.
I cannot write proposals, but I suppose we are working on a version of vilfredo where all questions are visible only for those invited, right ?

**Comment by pietrosperoni** [comment]
Yes, important and urgent

**Comment by derekpa** [comment]
Also, as well as putting in checks, I'm thinking we should be generating unique ID hashes for objects instead of using sequential indexes.

BTW I added an URGENT label. Makes it easier to see issues that might be of an urgent nature :-)

**Comment by derekpa** [comment]
Hmm, checks are there already. Must be a bug.

**Comment by derekpa** [comment]
Yes bug.

**Comment by derekpa** [comment]
fixed on live and demo (api v1). Will now add fixes to api v2 for test and nightly.

**Comment by derekpa** [comment]
Fixes applied to v2 of API on test.

**Comment by giovanisp** [comment]
Check my comments on line code by clicking 
![image](https://cloud.githubusercontent.com/assets/180794/6370345/973831bc-bcef-11e4-99f0-056533c38b20.png)


https://github.com/fairdemocracy/vilfredo-core/commit/be79244a64c8a1dc308733e328016f95e007ce29#diff-2fe50b04edf2480f3ac7e2ce482a7cbdR4097

**Comment by derekpa** [comment]
Why is this still open? 

Deciding on return cods would b a separate issue.

**Comment by giovanisp** [comment]
Because I get a Not Found instead of a Forbidden error (as this issue is about user data access).

**Comment by giovanisp** [comment]
Moved to final, so we can hurry up rc2.

**Comment by derekpa** [comment]
Not found makes more sense than forbidden. Forbidden indicates yes it exists.

**Comment by giovanisp** [comment]
Yes... And it exists, but I am not invited, thus unauthorized to see its contents. at least until we develop the "ask to be invited" feature...

**Comment by derekpa** [comment]
Sorry, I don;t follow you.

**Comment by giovanisp** [comment]
I just mean that if the question ID does not exist the messages should be "Question not found" 
but if The user tries to access a question ID that DOES exist, but Is not invited, the system should not respond with a "question not found" message as it is doing (I suppose) but with a "You are not invited to this question" (that is a 403 forbidden) error message.

**Comment by pietrosperoni** [comment]
What about in both cases giving a:
"either the question does not exist or you are not invited to it".
So we do not give out extra information, and we are precise.

**Comment by giovanisp** [comment]
No good, in the future we will allow for people to request access to questions you're not invited to.

Inviato da iPad

**Comment by pietrosperoni** [comment]
good point!
