### ISSUE TITLE
support "photo-only" type of questions

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#47]
the system has to support photo-only questions, that is, the proposals are made by only one photo on which the user can vote.

**Comment by giovanisp** [comment]
@pietrosperoni  is this a 2.0.0 feature ?

**Comment by pietrosperoni** [comment]
Yes, is pretty easy, and it is quite necessary as we need it for the logo and the design itself.

**Comment by giovanisp** [comment]
I remember that later than 2.0  :-/

**Comment by pietrosperoni** [comment]
Is it such a big deal? Or should we wait when we have the wizard? But then we need to wait for all the photo questions we have.
