### ISSUE TITLE
implement voting methods on continuous scale (1D)

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#48]
implement voting methods for 1 dimensional voting on a continuous scale for a given question.

**Comment by pietrosperoni** [comment]
This is useful for all the times we need to ask questions where it is not really meaningful to ask if someone did not understand a proposal

**Comment by derekpa** [comment]
Added in 2.0

**Comment by giovanisp** [comment]
Do we have unit tests for these running in nightly environment like we have for the other app calls? 


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Derek Paterson <notifications@github.com> 
Data: 06/05/2015  21:09  (GMT+01:00) 
A: fairdemocracy/vilfredo-core <vilfredo-core@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-core] implement voting methods on continuous scale (1D) (#48) 
 
Added in 2.0

**Comment by pietrosperoni** [comment]
Hi @giovanisp , I know the question was not asked to me, still I did not understand what you meant with:

>Do we have unit tests for these running in nightly environment like we have for the other app calls? 

I hope @derekpa understands you, if not maybe you could explain yourself more :-)

**Comment by giovanisp** [comment]
@derekpa knows what unit tests are :-)

**Comment by pietrosperoni** [comment]
Ok I shut up and stop putting my nose where it does not belong

**Comment by derekpa** [comment]
> Do we have unit tests for these running in nightly environment like we have for the other app calls? 

Nope. Good idea, I should add one.

**Comment by derekpa** [comment]
Will add an issue to  add  linear voting to unit tests to 2.1
