### ISSUE TITLE
Results page should allow users to see the resulting triangle, other than the winners

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#55]
showing only the winners might mislead those that skipped the voting phase for some reason (lack of time, etc...).

**Comment by pietrosperoni** [comment]
Indeed the resulting triangle, with the proposals in the pareto front in colored (in whatever shade of green they have achieved) and the other proposals in grey.

**Comment by giovanisp** [comment]
>the resulting triangle, with the proposals in the pareto front in colored (in whatever shade of green they have achieved) and the other proposals in grey

hmm... @pietrosperoni  is this what you were expecting ? it seems weird to me. I can't understand the color coding and what it means.

![image](https://cloud.githubusercontent.com/assets/180794/7683764/782dc160-fd81-11e4-9033-3cffa3aa3ead.png)

**Comment by pietrosperoni** [comment]
The winners are yellow.

I would say for now it is ok. Let's use this for some time, and then we have a better idea if it need to be enhanced :-)

**Comment by derekpa** [comment]
Actually its orange. Does it look yellow to you? Its just a colour that doesn't look too much like the one's we're using. It will surely do for now.

**Comment by giovanisp** [comment]
Ok, it was nice to add the proposal ID in the title bars as well so the user knows which proposal ID is related to which proposal title above.

**Comment by derekpa** [comment]
OK, I see :-). Th colour of the boxes matches your vote which you can see when you click on the winner.

We can perhaps do something to make this clearer in a later release.

**Comment by giovanisp** [comment]
please @derekpa open a new issue on 2.1

**Comment by pietrosperoni** [comment]
@giovanisp please, no.

I understand you want to close 2.0.0. But going through 2.1 will mean that a lot of other things will need to get through before those things are done.

**Comment by pietrosperoni** [comment]
We finish this stuff AND THEN we close 2.0.0

**Comment by derekpa** [comment]
Actually this issue should be for client not core.

**Comment by pietrosperoni** [comment]
Not sure why it's here. SHould we move it? Can you still complete it?

**Comment by giovanisp** [comment]
@pietrosperoni sorry, but you first closed this :-) https://github.com/fairdemocracy/vilfredo-core/issues/55#issuecomment-104391178   i just reopened for the ID in the title bar :-) and yes, my bad it should go on the client :-)
