### ISSUE TITLE
Prevent download of public user data unless user requesting is authorized

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-core#57]
Related to #46

**Comment by giovanisp** [comment]
absolutely to close before the final 2.0

**Comment by giovanisp** [comment]
check into OAuth for this. http://oauth.net/  and http://oauth.net/code/ (search for Python).

**Comment by derekpa** [comment]
Actually I am doing this using our existing code. There were some missing checks, hat's all. No need to look at Auth.
