### ISSUE TITLE
Fix participation table.

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-core#64]
Only show proposal counts for current generation

**Comment by pietrosperoni** [comment]
Actually if there are multiple generations it should show the previous generations in different columns as well, as it is important if someone is not participating only now, or he never really participated.

**Comment by derekpa** [comment]
No this was a bug where the proposal count should be only for one  generation in one column. You're talking about adding ciolums for each generation, which is different.

This bug was fixed.
