### ISSUE TITLE
update API documentation to 2.0 in dev.vilfredo.org

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-core#66]
rebuild Documentation with version 2.0 and publish under the /v2 folder in dev.vilfredo.org

**Comment by derekpa** [comment]
There's an updated document in a v2 folder now, ready for when we update the link.

Have a look through and see if I missed anythng

**Comment by giovanisp** [comment]
ok, there are many calls without sample code for usage and description... (scroll http://dev.vilfredo.org/v2/index.html#document-http_api) but I can understand it takes a lot of time. So I am postponing this along with new releases.

**Comment by giovanisp** [comment]
Time to add sample code.
