### ISSUE TITLE
Python Test fails

### ISSUE THREAD

**Issue by verdecchia** [fairdemocracy/vilfredo-core#72]
I'm installing vilfredo-core following the readme.rst (docs/source/readme.rst).
When I execute the "python manage.py test", test_api.py fail at row 203.

Here the complete log, hope it helps:

warning: no files found matching '*.rst'
no previously-included directories found matching 'dist'
test_rest_api (VilfredoReloadedCore.test.test_api.RESTAPITestCase) ... 
--------------------------------------------------------------------------------
DEBUG in test_api [/home/admin/vilfredo-core/VilfredoReloadedCore/test/test_api.py:60]:
Running tests on database sqlite:////var/db/vr.db
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in test_api [/home/admin/vilfredo-core/VilfredoReloadedCore/test/test_api.py:68]:
Initializing sqlite db

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in api [/home/admin/vilfredo-core/VilfredoReloadedCore/api/v2/api.py:839]:
api_create_user called...

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in api [/home/admin/vilfredo-core/VilfredoReloadedCore/api/v2/api.py:841]:
Request {u'username': u'john', u'password': u'john123', u'email': u'john@example.com'}...

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in test_api [/home/admin/vilfredo-core/VilfredoReloadedCore/test/test_api.py:203]:
Data retrieved from Create User = {
  "message": "Username not available"
}

--------------------------------------------------------------------------------
FAIL

======================================================================
FAIL: test_rest_api (VilfredoReloadedCore.test.test_api.RESTAPITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/admin/vilfredo-core/VilfredoReloadedCore/test/test_api.py", line 204, in test_rest_api
    self.assertEqual(rv.status_code, 201)
AssertionError: 400 != 201
-------------------- >> begin captured logging << --------------------
VilfredoReloadedCore: DEBUG: Running tests on database sqlite:////var/db/vr.db
VilfredoReloadedCore: DEBUG: Initializing sqlite db

VilfredoReloadedCore: DEBUG: api_create_user called...

VilfredoReloadedCore: DEBUG: Request {u'username': u'john', u'password': u'john123', u'email': u'john@example.com'}...

VilfredoReloadedCore: DEBUG: Data retrieved from Create User = {
  "message": "Username not available"
}

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.700s

FAILED (failures=1)

**Comment by pietrosperoni** [comment]
@giovanisp I think you are the best person to answer here :-)

**Comment by giovanisp** [comment]
@verdecchia I'm sorry we still do not have a fail-safe install documentation. Unfortnately we are late closing 2.0 and @derekpa who is the lead developer that can troubleshoot it is deeply committed into closing it. We have http://nightly.vilfredo.org that is built from the source every night. Perhaps something broke during the last updates, @derekpa ?
@verdecchia do you have the DB already in place? It seems the script that creates the demo users is trying to create a username which it says is already used.

**Comment by derekpa** [comment]
Failed for sqlite. Fixed.

**Comment by verdecchia** [comment]
thank you, it works!
