### ISSUE TITLE
Prevent proposals with identical titles for question

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-core#76]

**Comment by giovanisp** [comment]
I could send identical titles by just adding leading spaces in the title.
we need to trim leading and trailing spaces from the titles before saving them. And then compare titles.

**Comment by pietrosperoni** [comment]
And then you could get identical titles by substituting lower case Ls with upper case i. @giovanisp I don't think this is very urgent, we are trying to stop the errors, not the ill intention. Maybe we move this to later?

**Comment by giovanisp** [comment]
A "trim" is a half-line change in the code.
But yes, this is not high prio now.

**Comment by pietrosperoni** [comment]
ok, so let's go for the trim, and then that's it :-)

**Comment by derekpa** [comment]
Yes for trim, and no pietro text case should not effect it.
