### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('Flask-CDN==1.2.0')

### ISSUE THREAD

**Issue by tommasosperoni** [fairdemocracy/vilfredo-core#94]
On OS X 10.9.5
 > python setup.py develop

give me this error message: 

>Processing dependencies for VilfredoCore==2.0.0
Searching for Flask-CDN==1.2.0
Reading http://pypi.python.org/simple/Flask-CDN/
No local packages or download links found for Flask-CDN==1.2.0
error: Could not find suitable distribution for Requirement.parse('Flask-CDN==1.2.0')

**Comment by derekpa** [comment]
This package was deleted I think. Was updated to Flask-CDN==1.2.1 in commit a3d2050
